" To figure out what a current mapping is:
" :verbose map {key-combo} where
" key-combo is of the form <c-i> for Control I
"                          <D-r> for Command R
" :map and :map! show existing mappings
"
" TODO
" figure out statusline
" use %{fugitive#statusline()} for git info
"
" http://code.google.com/p/conque/  A shell in a VIM buffer
" http://www.vim.org/scripts/script.php?script_id=273  buffer to list tags
" :set complete=.,t   "limit complete to current file and ctags
" map <Leader>rt :!ctags --extra=+f --exclude=.git --exclude=log -R * `rvm gemdir`/gems/*<CR><CR>  "include gems in tags

" preserve default comma behavior as backslash (reverse of f,t search)
map \ ,
" Make certain to remap leader before other leader mappings
let mapleader = ","

" Vundle and bundles configuration
source ~/.vim/bundles.vim

set number
set ruler
set autoread
syntax on

set nobackup
set noswapfile
"set bufhidden "delete"
"shuts up LustyExplorer, but what are side-effects?
set hidden
set undodir=~/.vim/tmp
set undofile
"
"works in iTerm2, might also try =nicr or =i -- research
set mouse=a

map <Space> <PageDown>

" easier window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
" gf opens in tab
"nnoremap gf <C-W>gf

" split resizing by 50%
"nnoremap <silent> <Leader>+ :exe "resize " . (winheight(0) * 3/2)<CR>
"nnoremap <silent> <Leader>- :exe "resize " . (winheight(0) * 2/3)<CR>
"nnoremap <silent> <Leader>< :exe "vertical resize " (winwidth(0) * 3/2)<CR>
"nnoremap <silent> <Leader>> :exe "vertical resize " (winwidth(0) * 2/3)<CR>
nnoremap <silent> <leader>+ :resize +5<cr>
nnoremap <silent> <leader>- :resize +5<cr>
nnoremap <silent> <leader>> :vertical resize +5<cr>
nnoremap <silent> <leader>< :vertical resize -5<cr>

" Map <Leader>e to glob path matching (**/)
" CamelCaseMotion interferes with <leader>e
nmap <Leader>e :e **/
cmap <Leader>e **/
nmap <Leader>v :vsp **/
nmap <Leader>s :sp **/

set cursorline

" Whitespace stuff
set nowrap
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·

" Use mac system cliboard by Default. Which I don't think works in tmux
set clipboard=unnamed

"visual indicator of end of edit area
set cpoptions+=$
"set virtualedit=onemore "see h 'virtualedit'

"lines above/below cursor
set scrolloff=5
"intuitive locations of split windows
set splitbelow splitright
"allow virtual editing in visual block mode
set virtualedit=block

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc

" Status bar
set laststatus=2
set encoding=utf-8

" Hopefully a temporary mapping to deal with TFS write-only files
" map <Leader>q :!tf checkout %<CR>
"au BufWritePre * :if &readonly | !tf co <afile>

" Execute test in buffer
" nnoremap <leader>s :!ruby -rubygems -I app -I test %<CR>

" Command-T configuration (trying CtrlP instead)
"let g:CommandTMaxHeight=20
"let g:CommandTAcceptSelectionTabMap='<CR>'
"let g:CommandTAcceptSelectionMap='<C-t>'
"map <Leader>tf :CommandTFlush

" poor man's ZoomWin (doesn't restore)
map <Leader><Leader> :on<CR>

" CTags
map <Leader>rt :!ctags --extra=+f -R *<CR><CR>

" turn off search highlighting
nmap <silent> <Leader>/ :nohlsearch<CR>
" couldn't get the below working -- reuses existing redraw behavior
"nmap <silent> <C-l> :redraw \| nohlsearch<CR>
"imap <silent> <C-l> <Esc><C-L>a

" xml pretty print
map <Leader>px :%!xmllint --format --recover -<CR>

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

if !exists(":setupWrapping")
function! s:setupWrapping()
  set wrap
  set wm=2
  set textwidth=72
endfunction
endif

function! s:setupMarkup()
  call s:setupWrapping()
  map <buffer> <Leader>p :Mm <CR>
endfunction

" make and python use real tabs
au FileType make                                     set noexpandtab
au FileType python                                   set noexpandtab

" Thorfile, Rakefile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Thorfile,config.ru}    set ft=ruby

" md, markdown, and mk are markdown and define buffer-local preview
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} call s:setupMarkup()

au BufRead,BufNewFile *.txt call s:setupWrapping()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Opens an edit command with the path of the currently edited file filled in
" Normal mode: <Leader>e
"map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" Opens a tab edit command with the path of the currently edited file filled in
" Normal mode: <Leader>t
"map <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

" visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv

" Command mode: Ctrl+P inserts dir of current file
cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" Use modeline overrides
set modeline
set modelines=10

if !exists(":RubyHook")
  function! RubyHook()
      " formats K ri docs without embedded control chars
      setlocal keywordprg=ri\ -T\ -f\ bs 
  endfunction
endif

autocmd FileType ruby,eruby call RubyHook()

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif 

" Default color scheme
syntax enable
set background=dark
colorscheme solarized

"Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" to save after opening a readonly file
" cmap w!! w !sudo tee % >/dev/null

" enable very magic regexes by default
nnoremap / /\v
vnoremap / /\v

" toggle relative numbering
function! NumberToggle()
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc

nnoremap <silent> <F5> :call NumberToggle()<cr>

" Stolen from Learn Vimscript the Hard Way
" http://learnvimscriptthehardway.stevelosh.com/chapters/34.html
" ,g followed by any motion performs a grep for the match
nnoremap <leader>g :set operatorfunc=<SID>GrepOperator<cr>g@
vnoremap <leader>g :<c-u>call <SID>GrepOperator(visualmode())<cr>
function! s:GrepOperator(type)
  let saved_unnamed_register = @@

  if a:type ==# 'v'
    normal! `<v`>y
  elseif a:type ==# 'char'
    normal! `[v`]y
  else
    return
  endif

  silent execute "grep!  -R " . shellescape(@@) . " ."
  copen

  let @@ = saved_unnamed_register
endfunction

" Removes trailing spaces
function! TrimWhiteSpace()
    %s/\s\+$//e
endfunction

nnoremap <silent> <Leader>rts :call TrimWhiteSpace()<CR>

" xterm not recognized right by vim ?? this screws up cursor when exiting cli vim
" set term=builtin_ansi

let $MYTODO = '~/Dropbox/todo.taskpaper'

"auto-source this file on save
autocmd! BufWritePost $MYVIMRC source $MYVIMRC

" Include user's local vim config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

